-- 재고관리 통합 

-- 카테고리 테이블 드랍
drop table categories cascade constraint;

-- 재고상품 테이블 드랍
drop table products cascade constraint;


-- 카테고리 테이블 생성
create table categories (
    
    -- 카테고리 번호
    category_no number generated by default as identity primary key,
    
    -- 카테도리 이름
    cetegory_name varchar2(100) not null
    
);

-- 재공상품 테이블 생선
create table products (

    -- 상품번호
    product_no number generated by default as identity primary key,
    
    --상품명
    product_name varchar2(100) not null,
    
    --상품수량
    product_quantity number not null,
    
    --상품가격
    product_price number(10,2),
    
    --카테고리 번호
    category_no number,
    
    --상품등록일
    created_at date default sysdate,
    
    --업데이트일
    updated_at Date,
    
    -- 카테고리 테비을 FK
    constraint fk_category
        foreign key (category_no)
        references categories(category_no)
);

-- 트리거로 updated_at 자동 업데이트
create or replace trigger trg_product_update
BEFORE  update on products
for each ROW
begin
    :new.updated_at := sysdate;
end;
/


--  샘플데이터 등록
insert into categories (cetegory_name)
values('가전');

insert into categories (cetegory_name)
values('식품');

insert into categories (cetegory_name)
values('의류');

insert into products(product_name, product_quantity, product_price, category_no, created_at)
values('휴대폰', 142, 1450000, 1, TO_DATE('2025-08-30', 'YYYY-MM-DD'));


-- 생픔데이터 상품 업데이트
update products set product_quantity=200;

commit;
